## Mean of datasets
### Practice Quiz

In [394]:
import numpy as np

In [395]:
def get_mean_vector_from_matrix(matrix):
    size_of_vectors = np.array([np.size(vector) for vector in matrix])
    _mean_vector = np.array([[np.sum(matrix[i]) / size_of_vectors[i]] for i in range(0, np.size(size_of_vectors))])
    return _mean_vector

### 1. What is the mean of the dataset D = {1,2,3}?

In [396]:
d = np.array([1, 2, 3])
mean = np.sum(d) / np.size(d)
print(mean)

2.0


### 2. Compute the eman of the following dataset
```
D = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
```

In [397]:
d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(get_mean_vector_from_matrix(d))

[[2.]
 [5.]
 [8.]]


### 3. What is the mean of the following dataset, after multiplying each sample in the dataset by 2? 
```
D = [
    [1,3,5],
    [2,4,3],
    [3,5,1],
]
```

In [398]:
d = np.array([
    [1,3,5],
    [2,4,3],
    [3,5,1],
]) * 2
print(get_mean_vector_from_matrix(d))

[[6.]
 [6.]
 [6.]]


### 4. What is the mean of the following dataset, after adding `[[1],[2],[3]]` to each sample in the following dataset?
```
D = [
    [1,3,5],
    [2,4,3],
    [5,3,1]
]
```

In [399]:
d = np.array([
    [1,3,5],
    [2,4,3],
    [5,3,1]
]) + np.array([
    [1],
    [2],
    [3]
])
print(d)
print(f'mean of vector = {get_mean_vector_from_matrix(d)}')

[[2 4 6]
 [4 6 5]
 [8 6 4]]
mean of vector = [[4.]
 [5.]
 [6.]]


### 5. Assuming that we know the mean xn-1 of a dataset Dn -1 with n-1 data points. Now, suppose that we collect another data point, which we denote by x*. Select the correct formula that computes the correct new mean xn of the full data set Dn = Dn-1 U {x*}, i.e., we add x* to the dataset D.

In [400]:
# d = np.array([
#     [1,3,5,2],
#     [2,4,3,4],
#     [5,3,1,2]
# ])
# print(get_mean_vector_from_matrix(d))
# 2.75,3.25,2.75
d = np.array([
    [1,3,5],
    [2,4,3],
    [5,3,1]
])
new_vector = np.array([
    [2],
    [4],
    [2]
])
mean_vector = get_mean_vector_from_matrix(d)
print(mean_vector+(new_vector - mean_vector)/(np.size(mean_vector)+1))

[[2.75]
 [3.25]
 [2.75]]


### 6. Assuming you are given an image as a two-dimensional array of shape 28x28. Write a small piece of python code to reshape this image to a vector of length 784=(28x28) 

In [401]:
_matrix = np.array([
    [1,3,5],
    [2,4,3],
    [5,3,1]
])
print(_matrix.reshape(-1))

[1 3 5 2 4 3 5 3 1]
